# Generated by Django 2.0.1 on 2018-01-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=100)),
                ('team_name_kr', models.CharField(default='', max_length=100)),
                ('nation', models.CharField(default='', max_length=10)),
                ('stadium', models.CharField(default='', max_length=100)),
                ('stadium_kr', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
